# numpy practice

In [8]:
a=[1,2,3]
b=[2,3,5]
c=[]
for i in range(len(a)):
    c.append(a[i]+b[i])
print(c)

[3, 5, 8]


In [6]:
import numpy as np
a=np.array([[45,25,36],[4,6,8]])
b=np.array([[25,25,25],[5,6,9]])
add=a+b
sub=a-b
mul=a*b
divi=a/b
print("addition:",add)
print("substraction:",sub)
print("multiplication:",mul)
print("division:",divi)

addition: [[70 50 61]
 [ 9 12 17]]
substraction: [[20  0 11]
 [-1  0 -1]]
multiplication: [[1125  625  900]
 [  20   36   72]]
division: [[1.8        1.         1.44      ]
 [0.8        1.         0.88888889]]
