In [13]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])   # A 1D array with 12 elements
newarr = x.reshape(6,2,1)                               # Reshapes it into 4 rows and 3 columns
print(newarr)



[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]
