In [1]:
import numpy

In [2]:
a=numpy.array(5)
print(a)

5


In [4]:
import numpy
k=numpy.array(10)
print(k)

10


In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,])
print(a)
print(a.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [6]:
import numpy as np
print(np.__version__)


1.26.4


In [8]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.ndim)
        

[1 2 3]
1


In [16]:
import numpy as np
a=np.array([[1,2,3],[1,2]])
print(a)
print(a.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [11]:
import numpy as np
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3
